# Generated by Django 3.1.7 on 2021-03-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milkapp', '0004_complain_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complain',
            name='answered',
        ),
        migrations.AddField(
            model_name='complain',
            name='answer',
            field=models.TextField(default='Just a Default Ans'),
        ),
    ]
