# Generated by Django 3.1.7 on 2021-03-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milkapp', '0005_auto_20210315_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='answered',
            field=models.BooleanField(default=False),
        ),
    ]
