# Generated by Django 3.1.7 on 2021-03-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milkapp', '0008_subscription_last_delivered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='last_delivered',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
