# Generated by Django 3.1.7 on 2021-03-17 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('milkapp', '0010_auto_20210315_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryboynotifications',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='StoreNotifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='milkapp.store')),
            ],
        ),
    ]
