# Generated by Django 3.1.7 on 2021-03-18 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milkapp', '0012_auto_20210318_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'CASH'), ('JAZZ', 'JAZZ CASH'), ('EASYPAISA', 'EASYPAISA')], max_length=10),
        ),
    ]
