# Generated by Django 3.1.7 on 2021-03-19 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('milkapp', '0014_auto_20210319_0826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='timing',
        ),
        migrations.AddField(
            model_name='subscription',
            name='time_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='milkapp.timeslot'),
        ),
    ]
