# Generated by Django 3.1.7 on 2021-03-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milkapp', '0017_auto_20210319_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'CASH'), ('JAZZ', 'JAZZ CASH'), ('EASYPAISA', 'EASYPAISA')], default='CASH', max_length=10),
        ),
    ]
