# Generated by Django 3.1.7 on 2021-07-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milkapp', '0023_auto_20210719_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verify_code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
