# Generated by Django 3.1.7 on 2021-07-22 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('milkapp', '0024_user_verify_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryboy',
            name='storearea',
        ),
        migrations.AddField(
            model_name='storeareas',
            name='delivery_boy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='milkapp.deliveryboy'),
        ),
    ]
