# Generated by Django 3.1.7 on 2021-07-23 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milkapp', '0025_auto_20210723_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
