# Generated by Django 3.1.7 on 2021-07-23 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milkapp', '0026_auto_20210724_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='balance',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
