# Generated by Django 3.1.7 on 2021-08-18 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('milkapp', '0033_productsubcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsubcategory',
            name='image',
        ),
    ]
