# Generated by Django 3.1.7 on 2021-08-22 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('milkapp', '0036_auto_20210818_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlinepayment',
            name='image',
        ),
        migrations.AddField(
            model_name='onlinepayment',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='onlinepayment',
            name='superhash',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onlinepayment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='storeareas',
            name='delivery_boy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='area', to='milkapp.deliveryboy'),
        ),
    ]
