# Generated by Django 3.1.7 on 2021-09-04 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('milkapp', '0038_auto_20210823_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'CASH'), ('JAZZ', 'JAZZ CASH')], default='CASH', max_length=10),
        ),
        migrations.CreateModel(
            name='CanceledOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancelled_at', models.DateTimeField(auto_now=True)),
                ('reason', models.TextField()),
                ('cancelled_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='milkapp.order')),
            ],
        ),
    ]
