# Generated by Django 3.1.7 on 2021-09-12 15:46

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('milkapp', '0040_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
