# Generated by Django 3.1.7 on 2021-09-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milkapp', '0041_productcategory_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.CharField(default='NEXT', max_length=20),
        ),
    ]
