# Generated by Django 3.1.7 on 2021-09-23 13:51

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('milkapp', '0046_cancelledorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsubcategory',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
