# Generated by Django 3.1.7 on 2021-10-14 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('milkapp', '0047_productsubcategory_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsubcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='milkapp.productcategory'),
        ),
    ]
