# Generated by Django 3.1.7 on 2021-11-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milkapp', '0049_auto_20211023_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
