# Generated by Django 3.1.7 on 2021-03-15 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milkapp', '0002_auto_20210314_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complain',
            name='answer',
        ),
        migrations.AddField(
            model_name='complain',
            name='answered',
            field=models.BooleanField(default=False),
        ),
    ]
