# Generated by Django 3.1.7 on 2021-03-15 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milkapp', '0003_auto_20210315_0354'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='title',
            field=models.CharField(default='This is a Simple Query', max_length=255),
        ),
    ]
