# Generated by Django 3.1.7 on 2021-03-15 12:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('milkapp', '0007_auto_20210315_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='last_delivered',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
