# Generated by Django 3.1.7 on 2021-03-15 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milkapp', '0009_auto_20210315_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='timing',
            field=models.DateTimeField(),
        ),
    ]
