# Generated by Django 3.1.7 on 2021-03-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milkapp', '0015_auto_20210319_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryboynotifications',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryboynotifications',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
