# Generated by Django 3.1.7 on 2021-03-20 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milkapp', '0018_subscription_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryboy',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
