# Generated by Django 3.1.7 on 2021-03-20 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('milkapp', '0019_deliveryboy_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryboy',
            old_name='address',
            new_name='zone_address',
        ),
    ]
